name: Keploy CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Match your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize Database
        run: python database.py
      
      - name: Run Keploy API Tests
        uses: keploy/keploy-github-action@v1
        with:
          # The command to start your Flask application
          command: "flask run"
          # The keploy-app-name should be same as the app name in keploy.yml
          keploy-app-name: "my-python-api"